name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      #JDK 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      #cache
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      #Build e testes
      - name: Build & Test
        run: mvn clean package

      # Docker image
      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .

      